Repository SORTEE-Github-Hackathon/manuscript, pull requests merged in 2022-07, with the labels that each got.

#251 updates before preprinting
  content/01.abstract.md
  content/02.introduction.md
  content/03.use-cases-a.md
  content/04.use-cases-b.md
  content/05.use-cases-c.md
  content/06.discussion-a.md
  editorial-communication/cover-letter-submission.Rmd
Labels: edits, Priority: high

#255 fixing order of tables and modifying comparison table
  content/04.use-cases-b.md
  content/10.comparison_table.md
  content/11.roles_table.md
  data/comparison_table_raw.csv
Labels: figure, edits, Priority: high

#256 Changes before preprint
  content/02.introduction.md
  content/03.use-cases-a.md
  content/06.discussion-a.md
  content/10.comparison_table.md
Labels: edits, Priority: medium

#259 Updates cover letter with preprint link
  editorial-communication/cover-letter-submission.Rmd
Labels: edits, Priority: medium

#264 Few modifications to clarify a few points and decrease the length of certain parts
  content/02.introduction.md
  content/03.use-cases-a.md
  content/04.use-cases-b.md
  content/05.use-cases-c.md
  content/06.discussion-a.md
  content/07.conclusion.md
Labels: edits

#265 Adding use case: "Automation"
  R/scatterblob.Rmd
  R/scatterblob.html
  R/scatterblob.pdf
  content/01.abstract.md
  content/02.introduction.md
  content/03.use-cases-a.md
  content/05.use-cases-c.md
  content/06.discussion-a.md
  content/07.conclusion.md
  content/10.comparison_table.md
  content/11.comparison_table.md
  content/images/scatterblob_0.png
  content/images/scatterblob_1-viridis-turbo.png
  data/scatterblob_data_raw.csv
Labels: new text

#266 updates leaning lab link
  content/06.discussion-a.md
Labels: edits

#267 Changing "GitHub Organizations" to "Organizing and managing teams"
  R/scatterblob.html
  content/05.use-cases-c.md
  content/images/scatterblob_0.png
  content/images/scatterblob_1-viridis-turbo.png
  data/scatterblob_data_raw.csv
Labels: edits
