Repository SORTEE-Github-Hackathon/manuscript, pull requests merged in 2022-04, with the labels that each got.

#144 edits to use cases section a
  content/03.use-cases-a.md
Labels: edits

#142 Edits throughout introduction
  content/02.introduction.md
Labels: edits

#158 added paragraph on github as lab notebook
  content/03.use-cases-a.md
Labels: new text

#165 edits to conclusion
  content/07.conclusion.md
Labels: edits, Priority: medium

#152 Update 04.use-cases-b.md
  content/04.use-cases-b.md
Labels: new text

#168 Comparison table
  R/comparison_table.Rmd
  content/11.comparison_table.md
  data/comparison_table_raw.csv
Labels: new text, figure

#167 updated title and made some spelling updates
  README.md
  content/01.abstract.md
  content/02.introduction.md
  content/03.use-cases-a.md
  content/04.use-cases-b.md
  content/05.use-cases-c.md
Labels: edits

#166 Formatting and citation fixes of Abstract, Introduction, and Use Cases
  content/01.abstract.md
  content/02.introduction.md
  content/03.use-cases-a.md
  content/04.use-cases-b.md
  content/05.use-cases-c.md
Labels: edits

#170 Introducing cover letter draft and action
  .github/workflows/editorial-comm-render-build-deploy.yaml
  .gitignore
  editorial-communication/cover-letter-submission.Rmd
  editorial-communication/cover-letter-submission.html
  editorial-communication/skeleton.bib
Labels: enhancement

#164 edits to discussion
  content/06.discussion-a.md
Labels: edits, Priority: medium
