Repository SORTEE-Github-Hackathon/manuscript, pull requests merged in 2022-06, with the labels that each got.

#218 Repo to repository and fixed a typo
  R/roles_table.Rmd
  content/09.figures-tables.md
  content/10.roles_table.md
  content/11.comparison_table.md
  data/collaborator_roles.csv
  data/comparison_table_raw.csv
Labels: edits, Priority: medium

#228 Decreasing the length of the text and improving consistency of the narrative: `03.use-cases-a.md`
  content/03.use-cases-a.md
Labels: enhancement

#234 making required changes to figure 1
  content/images/github.svg
  content/images/github_diagram.png
Labels: figure, edits, Priority: high

#237 update figure caption
  content/09.figures-tables.md
Labels: edits, Priority: high
